=== rezapurnamaa/Java/vsys/uebung4/resources/professor.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
  <xs:element name="Professor">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="vorname"/>
        <xs:element type="xs:string" name="nachname"/>
        <xs:element name="wohnort">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="strasse"/>
              <xs:element type="xs:string" name="hausnr"/>
              <xs:element type="xs:string" name="plz"/>
              <xs:element type="xs:string" name="stadt"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:date" name="geburtsdatum"/>
        <xs:element type="xs:string" name="fachbereich"/>
        <xs:element type="xs:string" name="personalnummer"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rezapurnamaa/Java/vsys/professor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Professor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="professor.xsd">
    <vorname>Hans</vorname>
    <nachname>Schlauberger</nachname>
    <wohnort>
        <strasse>Elfenbeinturm</strasse>
        <hausnr>42</hausnr>
        <plz>76543</plz>
        <stadt>Wiesbaden</stadt>
    </wohnort>
    <geburtsdatum>1972-05-12</geburtsdatum>
    <fachbereich>FB 4</fachbereich>
    <personalnummer>999999</personalnummer>
</Professor>

=== rezapurnamaa/Java/vsys/uebung4/professor.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Professor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="professor.xsd">
    <vorname>Prenzlauer</vorname>
    <nachname>Berger</nachname>
    <wohnort>
        <strasse>Prenzlauer Allee</strasse>
        <hausnr>22</hausnr>
        <plz>10247</plz>
        <stadt>Berlin</stadt>
    </wohnort>
    <geburtsdatum>1900-01-01</geburtsdatum>
    <fachbereich>FB 4</fachbereich>
    <personalnummer>123456</personalnummer>
</Professor>
