=== rezapurnamaa/Java/vsys/resources/student.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
<xs:element name="Student">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="vorname"/>
        <xs:element type="xs:string" name="nachname"/>
        <xs:element name="wohnort">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="strasse"/>
              <xs:element type="xs:string" name="hausnr"/>
              <xs:element type="xs:string" name="plz"/>
              <xs:element type="xs:string" name="stadt"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="matrikelnummer"/>
        <xs:element type="xs:string" name="studiengang"/>
        <xs:element type="xs:int" name="fachsemester"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rezapurnamaa/Java/vsys/student.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
    <vorname>Ilse</vorname>
    <nachname>Bilse</nachname>
    <wohnort>
        <strasse>Im Wald</strasse>
        <hausnr>12a</hausnr>
        <plz>12345</plz>
        <stadt>Berlin</stadt>
    </wohnort>
    <matrikelnummer>543210</matrikelnummer>
    <studiengang>Angewandtes Computerspielen</studiengang>
    <fachsemester>2</fachsemester>
</Student>

=== rezapurnamaa/Java/vsys/uebung4/student.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="student.xsd">
    <vorname>Max</vorname>
    <nachname>Mustermann</nachname>
    <wohnort>
        <strasse>Musterstr</strasse>
        <hausnr>123a</hausnr>
        <plz>12345</plz>
        <stadt>Berlin</stadt>
    </wohnort>
    <matrikelnummer>545344</matrikelnummer>
    <studiengang>AI</studiengang>
    <fachsemester>1</fachsemester>
</Student>
